#include "roku_tv_layout.h"
#include "roku_tv_icons.h"

const RemoteButtonDef roku_tv_button_defs[ButtonMax] = {
    [ButtonPower] = {
        .label = NULL,
        .icon = &I_power_19x20,
        .selected_icon = &I_power_hover_19x20,
        .x = 22,
        .y = 0,
        .width = 19,
        .height = 20,
        .nav_up = ButtonPower,
        .nav_down = ButtonGuide,
        .nav_left = ButtonPower,
        .nav_right = ButtonPower,
    },

    [ButtonHome] = {
        .label = NULL,
        .icon = &I_home_20x9,
        .selected_icon = &I_home_20x9_hover,
        .x = 1,
        .y = 22,
        .width = 20,
        .height = 9,
        .nav_up = ButtonPower,
        .nav_down = ButtonUp,
        .nav_left = ButtonHome,
        .nav_right = ButtonGuide,
    },
    [ButtonGuide] = {
        .label = NULL,
        .icon = &I_guide_20x9,
        .selected_icon = &I_guide_20x9_hover,
        .x = 22,
        .y = 22,
        .width = 20,
        .height = 9,
        .nav_up = ButtonPower,
        .nav_down = ButtonUp,
        .nav_left = ButtonHome,
        .nav_right = ButtonReturn,
    },
    [ButtonReturn] = {
        .label = NULL,
        .icon = &I_Pin_back_arrow_10x8,
        .selected_icon = NULL,
        .x = 48,
        .y = 22,
        .width = 10,
        .height = 8,
        .nav_up = ButtonPower,
        .nav_down = ButtonUp,
        .nav_left = ButtonGuide,
        .nav_right = ButtonReturn,
    },

    [ButtonUp] = {
        .label = NULL,
        .icon = &I_ButtonUp_7x4,
        .selected_icon = NULL,
        .x = 28,
        .y = 35,
        .width = 7,
        .height = 4,
        .nav_up = ButtonGuide,
        .nav_down = ButtonOk,
        .nav_left = ButtonUp,
        .nav_right = ButtonUp,
    },
    [ButtonLeft] = {
        .label = NULL,
        .icon = &I_ButtonLeft_4x7,
        .selected_icon = NULL,
        .x = 17,
        .y = 45,
        .width = 4,
        .height = 7,
        .nav_up = ButtonUp,
        .nav_down = ButtonDown,
        .nav_left = ButtonLeft,
        .nav_right = ButtonOk,
    },
    [ButtonOk] = {
        .label = NULL,
        .icon = &I_ButtonCenter_7x7,
        .selected_icon = NULL,
        .x = 28,
        .y = 45,
        .width = 7,
        .height = 7,
        .nav_up = ButtonUp,
        .nav_down = ButtonDown,
        .nav_left = ButtonLeft,
        .nav_right = ButtonRight,
    },
    [ButtonRight] = {
        .label = NULL,
        .icon = &I_ButtonRight_4x7,
        .selected_icon = NULL,
        .x = 43,
        .y = 45,
        .width = 4,
        .height = 7,
        .nav_up = ButtonUp,
        .nav_down = ButtonDown,
        .nav_left = ButtonOk,
        .nav_right = ButtonRight,
    },
    [ButtonDown] = {
        .label = NULL,
        .icon = &I_ButtonDown_7x4,
        .selected_icon = NULL,
        .x = 28,
        .y = 58,
        .width = 7,
        .height = 4,
        .nav_up = ButtonOk,
        .nav_down = ButtonVolumeUp,
        .nav_left = ButtonDown,
        .nav_right = ButtonDown,
    },

    [ButtonVolumeUp] = {
        .label = NULL,
        .icon = &I_volup_24x21,
        .selected_icon = &I_volup_hover_24x21,
        .x = 3,
        .y = 66,
        .width = 24,
        .height = 21,
        .nav_up = ButtonDown,
        .nav_down = ButtonVolumeDown,
        .nav_left = ButtonVolumeUp,
        .nav_right = ButtonChannelUp,
    },
    [ButtonChannelUp] = {
        .label = NULL,
        .icon = &I_ch_up_24x21,
        .selected_icon = &I_ch_up_hover_24x21,
        .x = 37,
        .y = 66,
        .width = 24,
        .height = 21,
        .nav_up = ButtonDown,
        .nav_down = ButtonChannelDown,
        .nav_left = ButtonVolumeUp,
        .nav_right = ButtonChannelUp,
    },
    [ButtonVolumeDown] = {
        .label = NULL,
        .icon = &I_voldown_24x21,
        .selected_icon = &I_voldown_hover_24x21,
        .x = 3,
        .y = 89,
        .width = 24,
        .height = 21,
        .nav_up = ButtonVolumeUp,
        .nav_down = ButtonNetflix,
        .nav_left = ButtonVolumeDown,
        .nav_right = ButtonChannelDown,
    },
    [ButtonChannelDown] = {
        .label = NULL,
        .icon = &I_ch_down_24x21,
        .selected_icon = &I_ch_down_hover_24x21,
        .x = 37,
        .y = 89,
        .width = 24,
        .height = 21,
        .nav_up = ButtonChannelUp,
        .nav_down = ButtonDisney,
        .nav_left = ButtonVolumeDown,
        .nav_right = ButtonChannelDown,
    },

    [ButtonNetflix] = {
        .label = NULL,
        .icon = &I_netflix_28x8,
        .selected_icon = &I_netflix_hover_28x8,
        .x = 2,
        .y = 111,
        .width = 28,
        .height = 8,
        .nav_up = ButtonVolumeDown,
        .nav_down = ButtonPrimeVideo,
        .nav_left = ButtonNetflix,
        .nav_right = ButtonDisney,
    },
    [ButtonDisney] = {
        .label = NULL,
        .icon = &I_disney_28x8,
        .selected_icon = &I_disney_28x8_hover,
        .x = 34,
        .y = 111,
        .width = 28,
        .height = 8,
        .nav_up = ButtonChannelDown,
        .nav_down = ButtonAppleTv,
        .nav_left = ButtonNetflix,
        .nav_right = ButtonDisney,
    },
    [ButtonPrimeVideo] = {
        .label = NULL,
        .icon = &I_prime_28x8,
        .selected_icon = &I_prime_28x8_hover,
        .x = 2,
        .y = 120,
        .width = 28,
        .height = 8,
        .nav_up = ButtonNetflix,
        .nav_down = ButtonPrimeVideo,
        .nav_left = ButtonPrimeVideo,
        .nav_right = ButtonAppleTv,
    },
    [ButtonAppleTv] = {
        .label = NULL,
        .icon = &I_appletv_28x8,
        .selected_icon = &I_appletv_28x8_hover,
        .x = 34,
        .y = 120,
        .width = 28,
        .height = 8,
        .nav_up = ButtonDisney,
        .nav_down = ButtonAppleTv,
        .nav_left = ButtonPrimeVideo,
        .nav_right = ButtonAppleTv,
    },
};
